### ISSUE TITLE
Problem with DatePicker & TimePicker on creation popup

### ISSUE THREAD

**Issue by swrtom** [saade/filament-fullcalendar#109]
Hello
I'm not able to use "default()" and "minDate()" functions for DatePicker/TimePicker on getCreateEventFormSchema() while it works on plain FilamentPHP form (Eg. on Resource::form() function). I tried with several formats but it is not working :
`
protected static function getCreateEventFormSchema(): array
    {
        return [
            DatePicker::make('journee')
                ->required()
                ->label('Journée')
                ->default(now())
                ->minDate(now()->subDay(1)),
            TimePicker::make('start')
                ->label('Début')
                ->default(now())
                ->seconds(false)
                ->required(),
            TimePicker::make('end')
                ->label('Fin')
                ->default(now())
                ->seconds(false)
                ->required(),
            Select::make('user')
                ->label('Elève')
                ->options(User::all()->sortBy('name')->pluck('name', 'id'))
                ->searchable()
                ->default(null),
            Toggle::make('is_paid')
                ->label('Est payé')
        ];
    }
`

![image](https://github.com/saade/filament-fullcalendar/assets/44288315/bb38fb3c-8749-43ff-8cb2-61ae41167241)

Version of the package : ^3.0.0-beta

**Comment by swrtom** [comment]
Maybe it's due to this error, I am digging
![image](https://github.com/saade/filament-fullcalendar/assets/44288315/3e403318-277c-43c5-aec0-0c90a9e60492)

**Comment by swrtom** [comment]
I tried this but not able to remove "fullcalendar is not defined" error :
![image](https://github.com/saade/filament-fullcalendar/assets/44288315/c5cd4874-65af-4fd1-833c-fcb8ee6dcb27)

I also tried with linking filament-fullcalendar.js as the path given above doesn't exists in my vendors
![image](https://github.com/saade/filament-fullcalendar/assets/44288315/a60f3916-f9b4-40fd-9b33-4f8554ccc975)

**Comment by bobwurtz** [comment]
@sheepbild I am experiencing the same issue. Have you been able to solve this? It is affecting my ability to refresh the events.

**Comment by saade** [comment]
> @sheepbild I am experiencing the same issue. Have you been able to solve this? It is affecting my ability to refresh the events.

v3 is out, please give it a try and see if you're still facing issues

**Comment by bobwurtz** [comment]
@saade Yup, it's gone. Thank you! Now I get a `Unknown option 'schedulerLicenseKey'` warning but it's not an error. I'll let you know if that starts causing problems.

By the way, I think you have a typo in your docs. In the [Configuration](https://github.com/saade/filament-fullcalendar#configuration) section where it says `->fullCalendarConfig()`, I think you mean `->config()` - this is how you refer to it later. I get an undefined method error when I use `->fullCalendarConfig()`.

**Comment by saade** [comment]
> @saade Yup, it's gone. Thank you! Now I get a `Unknown option 'schedulerLicenseKey'` warning but it's not an error. I'll let you know if that starts causing problems.
> 
> 
> 
> By the way, I think you have a typo in your docs. In the [Configuration](https://github.com/saade/filament-fullcalendar#configuration) section where it says `->fullCalendarConfig()`, I think you mean `->config()` - this is how you refer to it later. I get an undefined method error when I use `->fullCalendarConfig()`.

Oh yeah, i should probably only add `schedulerLicenseKey` to the calendar if the `resourceTimeline` plugin is active. But this warning shouldn't cause any problems.

And yes, its `config` not `fullcalendarConfig` thanks for pointing that out

**Comment by albertobenavides** [comment]
I dont know if this is related, but Im getting this: 
![image](https://github.com/saade/filament-fullcalendar/assets/9291085/258059bb-1454-4c43-8141-c25ddc2eaf45)

Also, I cant enable selectable option. Thats why I think this might be related.
