### ISSUE TITLE
Upgraded to v3.0, there is a typo in fullcalendar.blade.php

### ISSUE THREAD

**Issue by paperscissors** [saade/filament-fullcalendar#111]
https://github.com/saade/filament-fullcalendar/blob/19021baff5798ffcf9c6661f8580146b7ca5692f/resources/views/fullcalendar.blade.php#L2C70-L2C70

The call to assign to $plugin is not properly cased
```$plugin = \Saade\FilamentFullcalendar\FilamentFullcalendarPlugin::get();```

should be

```$plugin = \Saade\FilamentFullCalendar\FilamentFullCalendarPlugin::get();```

**Comment by swrtom** [comment]
I confirm, same problem here
