### ISSUE TITLE
Inconsistence between the code and the README.md

### ISSUE THREAD

**Issue by chickgit** [saade/filament-fullcalendar#115]
in [here](https://github.com/saade/filament-fullcalendar#returning-events) you mentioned that to open url in new tab by providing `'shouldOpenUrlInNewTab' => true`

but in this code 
https://github.com/saade/filament-fullcalendar/blob/90a3adab4ecd1ebd5f04903d4a1993aef9119716/resources/js/filament-fullcalendar.js#L51-L55
the 'shouldOpenUrlInNewTab' is inside extendedProps.

right now im using  'shouldOpenUrlInNewTab' inside extendedProps so that event can opened in new tab.

**Comment by saade** [comment]
Its intended, every extraneous property gets pushed to extendedPros.
