### ISSUE TITLE
Exception Plugin [filament-fullcalendar] is not registered for panel [app].

### ISSUE THREAD

**Issue by paperscissors** [saade/filament-fullcalendar#123]
Laravel v10.28.0
Filament v3.0.73
filament-fullcalendar v3.0.3

I've upgraded Filament and then followed all of the steps in the README on here, and persistently get this error message when I load my dashboard. 

I've got the plugin registered on the bottom of my AdminPanelProvider in the panel() method like this:

```
->plugin(
                FilamentFullCalendarPlugin::make()
                    ->selectable()
                    ->editable()
                    ->timezone('local')
                    ->locale('en')
                    ->plugins([])
                    ->config([])
            );
```

I've got the CalendarWidget registered properly in my Dashboard:
```
public function getWidgets(): array
    {
        return 
            RequestsByCountyChart::class,
            RequestsThroughTimeChart::class,
            NetRequestIncomeChart::class,
            CalendarWidget::class,
        ];
    }
```

I've used previously versions of the plugin and it's worked fine. Am I missing something or is there some other issue implicated here?

**Comment by sinnbeck** [comment]
You mention `AdminPanelProvider` but the error says that the panel is named `app`, not `admin`. Got more than one panel perhaps?

**Comment by paperscissors** [comment]
I've just got the single panel. It's possible that there is some inconsistency with the panel naming though, because this was just upgraded to Filament 3.

**Comment by paperscissors** [comment]
Yes, I think this is just an issue with the Filament upgrade path, it had nothing to do explicitly with this plugin. Thanks!

**Comment by jhoanborges** [comment]
In my case i had 

```
           ->plugin(
Hasnayeen\Themes\ThemesPlugin::make(),
                FilamentFullCalendarPlugin::make()
                ->selectable()
                ->editable()
                ->locale('es')
                ->timezone('local')
                ->plugins([])
                ->config([])
                \
                //->schedulerLicenseKey()
            );
```

so, changing the order of plugings worked.
```

           ->plugin(
                FilamentFullCalendarPlugin::make()
                ->selectable()
                ->editable()
                ->locale('es')
                ->timezone('local')
                ->plugins([])
                ->config([]),
                \Hasnayeen\Themes\ThemesPlugin::make(),
                //->schedulerLicenseKey()
            );
```
Source: https://www.answeroverflow.com/m/1192802009548595320
