### ISSUE TITLE
 Option 'config' in 'AdminPanelProvider' overrides the 'config' method of the widget.

### ISSUE THREAD

**Issue by glauberdjs** [saade/filament-fullcalendar#173]
It is not possible to change the calendar settings in the widget, nor leave the config option empty in AdminPanelProvider to use the one from the widget.

Classes below:

![teste](https://github.com/saade/filament-fullcalendar/assets/112635086/f58453a2-182d-4c5a-bd21-f18ffedad355)
![teste (2)](https://github.com/saade/filament-fullcalendar/assets/112635086/5b6b8c72-5761-4c9a-8305-9602e3a5578d)

Of course, I have other functions related to my project, but here's what's important for the issue. Note that the config arrays are different, however, the AdminPanelProvider is not altered, and I need to change it in real-time in the view according to specific attributes of each client.

**Comment by saade** [comment]
The config in the AdminPanelProvider is used to apply global configuration to all your calendars, the method inside the class is used to customise per-widget. I'm not following the issue?

**Comment by glauberdjs** [comment]
But here's the issue: the local `config` method didn't change the calendar in the local widget. It retained the settings from the `AdminPanelProvider` instead of inheriting those from the widget.

**Comment by glauberdjs** [comment]
Is this my blade, is everything correct?

![codeimg-instagram-photo-thumbnail](https://github.com/saade/filament-fullcalendar/assets/112635086/877233e3-d47b-4aa9-b2b0-bc3a7988ee8d)

**Comment by glauberdjs** [comment]
I just noticed that the FullCalendarWidget doesn't have the config method, I believe that might be the issue. This is right?
![base_project](https://github.com/saade/filament-fullcalendar/assets/112635086/2f66e553-21d6-4721-9904-408b831d76a3)

**Comment by saade** [comment]
> I just noticed that the FullCalendarWidget doesn't have the config method, I believe that might be the issue. This is right?

You're not on the latest version then.

**Comment by glauberdjs** [comment]
You're right, my fault. It was on version 3.0. Thank you for the support!

**Comment by albertobenavides** [comment]
Hello. I am trying to set the minTime or minSlotTime in my calendarwidget, but, nothing changes if the config is defined in the plugin. I am at v. 3.0.

This is my Admin config:
```php
FilamentFullCalendarPlugin::make()
                    ->selectable()
                    // ->editable()
                    ->timezone('America/Monterrey')
                    ->locale('es')
                    ->plugins(['timeGrid', 'list'])
                    ->config([
                        'slotMinTime' => "06:00:00",
                        'slotMaxTime' => "23:00:00",
                        'initialView' => 'timeGridWeek',
                        'headerToolbar' => [
                            'left' => 'prev,next today',
                            'center' => 'title',
                            'right' => 'timeGridWeek,dayGridMonth,listWeek'
                        ],
                    ])
```

And my widget config:
```php
public function config(): array
    {
        return [
            'slotMinTime' => "09:00:00",
            'slotMaxTime' => "18:00:00",
            'minTime' => "09:00:00",
            'maxTime' => "18:00:00",
        ];
    }
```

**Comment by ana-lisboa** [comment]
> > I just noticed that the FullCalendarWidget doesn't have the config method, I believe that might be the issue. This is right?
> 
> You're not on the latest version then.

Isn't this the latest version? https://github.com/saade/filament-fullcalendar/blob/3.x/src/Widgets/FullCalendarWidget.php
I've just installed the plugin on a new project, and the FullCalendarWidget still does not have the config method. 

(composer.json: "saade/filament-fullcalendar": "3.0",)

**Comment by saade** [comment]
> Isn't this the latest version? https://github.com/saade/filament-
> (composer.json: "saade/filament-fullcalendar": "3.0",)

@ana-lisboa 

The latest version is [3.2.2](https://github.com/saade/filament-fullcalendar/releases/tag/v3.2.2), your composer json is locked to 3.0. Change it to `^3.0` and run composer update
