### ISSUE TITLE
It doesn't work if you add a plugin

### ISSUE THREAD

**Issue by theqewk** [saade/filament-fullcalendar#186]
Any addition of a plugin to the Provider Panel causes an error!
![1](https://github.com/saade/filament-fullcalendar/assets/80746594/56800568-2644-481f-8bb5-b1e9cb67be40)
![2](https://github.com/saade/filament-fullcalendar/assets/80746594/89c5a306-5555-4039-8dbe-c373f6ba6cfe)

**Comment by lukacavic** [comment]
I have same error!

**Comment by theqewk** [comment]
> I have same error!

It is necessary to use the resourceTimeline instead of the resourceTimelinePlugin, not as in the FullCalendar examples

`->plugins(['resourceTimeline'])`
