### ISSUE TITLE
The previous month's event does not carry over to the next month.

### ISSUE THREAD

**Issue by nickjangveladze** [saade/filament-fullcalendar#191]
I have 2 events:

1. From July 27th to August 8th.
2. From August 9th to August 17th.

For example, when I'm in July, the first event is visible from July 27th to August 9th, but when I move to August, the first event is not visible until August 9th. Only the second event is visible from August 9th to August 17th.

**July**
<img width="1491" alt="Screenshot 2024-06-10 at 22 00 57" src="https://github.com/saade/filament-fullcalendar/assets/13145816/19eca1bc-013e-4ab9-a721-2ceecc989e76">
**August**
<img width="1489" alt="Screenshot 2024-06-10 at 22 01 52" src="https://github.com/saade/filament-fullcalendar/assets/13145816/56eb5432-a36d-4ba1-bb29-5df921c2b31e">

**Comment by taher-k5** [comment]
@nickjangveladze  I am facing the same issue. Were you able to resolve it? 
Can we use Recurring Events here?

**Comment by saade** [comment]
@nickjangveladze @taher-k5 isnt that just a query issue?

`$fetchInfo['start']` would be `2024-08-01` when you're in August, excluding the events that started in July

**Comment by taher-k5** [comment]
but @saade If my event is 3 months long then What can I do?
Can you also share some examples related to Recurring Events?

**Comment by saade** [comment]
I hope my comment above fixed your issue, please reopen this if needed.

**Comment by YonkoSam** [comment]
so whats the fix ? i dont get it

**Comment by taher-k5** [comment]
@YonkoSam
You need to remove where condition from query in fetchEvents function

```
public function fetchEvents(array $fetchInfo): array
    {
        return Event::query()
            ->where('starts_at', '>=', $fetchInfo['start']) // remove this
            ->where('ends_at', '<=', $fetchInfo['end']) // remove this
            ->get()
            ->map(
                fn (Event $event) => [
                    'title' => $event->id,
                    'start' => $event->starts_at,
                    'end' => $event->ends_at,
                    'url' => EventResource::getUrl(name: 'view', parameters: ['record' => $event]),
                    'shouldOpenUrlInNewTab' => true
                ]
            )
            ->all();
    }
```

**Comment by YonkoSam** [comment]
wouldn't that make it very bad optimized to query all the task each time

**Comment by mgkimsal** [comment]
@YonkoSam  You could subtract one month from the 'start' during your fetch, so you'd get anything that started in the previous month.  Looking at August?  Find events from July 1 - Aug 31, etc.

Or... further back if you have any events that might span 2 months, etc.
