### ISSUE TITLE
Argument #2 ($record) - null given

### ISSUE THREAD

**Issue by mgkimsal** [saade/filament-fullcalendar#198]
Filament\Actions\ViewAction::Filament\Actions\{closure}(): Argument #2 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /app/vendor/filament/support/src/Concerns/EvaluatesClosures.php on line 35

I'm getting this when I click an event and it's trying to open an edit modal.  

This is just using current filament and plugin versions, just walking through the example code - no major integration with anything else.

Has something recently changed that might trigger this?

**Comment by saade** [comment]
Hey! Can you share some related code? Just tested here and it seems to work properly.

https://github.com/saade/filament-fullcalendar/assets/14329460/0703ba90-34dc-4c71-9e37-843628e2563d

**Comment by mgkimsal** [comment]
@saade  - apologies!  I got pulled away to other aspects of the project.  I will be looking back at this later this week!

**Comment by mgkimsal** [comment]
Going to close this - I rebuilt some of the code and it's working.
