### ISSUE TITLE
Cannot unpack array with string keys

### ISSUE THREAD

**Issue by lovemintblue** [saade/filament-fullcalendar#23]
There was an error following the tutorial
environment： laravel9.18.  filament:dev

**Comment by wychoong** [comment]
please provide more info and your code

**Comment by saade** [comment]
hi, @lovemintblue probably because you're returning arrays like this (associative arrays)

```php
return [
 'some-string-key' => [
  // event data
 ]
]
```

Be sure to only return the values from your array

```php
return [
 [
  // event data
 ]
]
```

but please, share the piece of code you're using so we can help you

**Comment by lovemintblue** [comment]
> hi, @lovemintblue probably because you're returning arrays like this (associative arrays)
> 
> ```
> return [
>  'some-string-key' => [
>   // event data
>  ]
> ]
> ```
> 
> Be sure to only return the values from your array
> 
> ```
> return [
>  [
>   // event data
>  ]
> ]
> ```
> 
> but please, share the piece of code you're using so we can help you

thanks you! fetchEvents is return empty array, I should to use CantManageEvents.

**Comment by saade** [comment]
> > hi, @lovemintblue probably because you're returning arrays like this (associative arrays)
> > ```
> > return [
> >  'some-string-key' => [
> >   // event data
> >  ]
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Be sure to only return the values from your array
> > ```
> > return [
> >  [
> >   // event data
> >  ]
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but please, share the piece of code you're using so we can help you
> 
> thanks you! fetchEvents is return empty array, I should to use CantManageEvents.

`CantManageEvents` is not meant to be used for this situation, it is used just to disable calendar interactions (create, edit)

you dont need to use fetchEvents, you can just remove the method from your class

**Comment by theavuth9** [comment]
I'm the same issue and here is my code:

Code version:
- php `8.0.x`
- filament `^2.0`
- filament-fullcalendar `^1.0`

CalendarWidget.php
```php
class CalendarWidget extends FullCalendarWidget
{
    /**
     * Return events that should be rendered statically on calendar.
     */
    public function getViewData(): array
    {
        return static::getAppointments(now()->subMonths(1), now()->addMonths(1));
    }

    /**
     * FullCalendar will call this function whenever it needs new event data.
     * This is triggered when the user clicks prev/next or switches views on the calendar.
     */
    public function fetchEvents(array $fetchInfo): array
    {
        $timezone = $this->config('timeZone', config('app.timezone'));

        $start = Carbon::parse($fetchInfo['start'], $timezone);
        $end = Carbon::parse($fetchInfo['end'], $timezone);

        return static::getAppointments($start, $end);
    }

    public static function getAppointments(Carbon $start, Carbon $end): array
    {
        $appointments = Appointment::query()
            ->where([
                ['start_time', '>=', $start],
                ['end_time', '<=', $end],
            ])
            ->get();

        return $appointments->map(function ($appointment) {
                return [
                    'id' => $appointment->id,
                    'title' => $appointment->title,
                    'start' => $appointment->start_time,
                    'end' => $appointment->end_time,
                ];
            })
            ->toArray();
    }

    protected static function getCreateEventFormSchema(): array
    {
        return [
            Forms\Components\TextInput::make('title')
                ->required(),
            Forms\Components\DatePicker::make('start')
                ->required(),
            Forms\Components\DatePicker::make('end')
                ->default(null),
        ];
    }

    /**
     * Triggered when the user clicks an event.
     *
     * Commented out so we can save some requests :) Feel free to extend it.
     * @see https://fullcalendar.io/docs/eventClick
     */
    public function onEventClick($event): void
    {
        //
    }
    
    /**
     * Triggered when dragging stops and the event has moved to a different day/time.
     *
     * Commented out so we can save some requests :) Feel free to extend it.
     * @see https://fullcalendar.io/docs/eventDrop
     */
    public function onEventDrop($oldEvent, $newEvent, $relatedEvents): void
    {
        //
    }

    public static function canCreate(): bool
    {
        // Returning 'false' will remove the 'Create' button on the calendar.
        return true;
    }

    public static function canEdit(?array $event = null): bool
    {
        // Returning 'false' will disable the edit modal when clicking on a event.
        return true;
    }
}
```

The result error like picture below:
![screenshot-filament g24-2022 07 14-21_25_18](https://user-images.githubusercontent.com/88300666/179005924-fe09bd9a-f4f9-4f11-a371-504e5efcf594.png)

Any help?
Thanks in advance

**Comment by saade** [comment]
> I'm the same issue and here is my code:
> 
> Code version:
> 
> * php `8.0.x`
> * filament `^2.0`
> * filament-fullcalendar `^1.0`
> 
> CalendarWidget.php
> 
> ```
> class CalendarWidget extends FullCalendarWidget
> {
>     /**
>      * Return events that should be rendered statically on calendar.
>      */
>     public function getViewData(): array
>     {
>         return static::getAppointments(now()->subMonths(1), now()->addMonths(1));
>     }
> 
>     /**
>      * FullCalendar will call this function whenever it needs new event data.
>      * This is triggered when the user clicks prev/next or switches views on the calendar.
>      */
>     public function fetchEvents(array $fetchInfo): array
>     {
>         $timezone = $this->config('timeZone', config('app.timezone'));
> 
>         $start = Carbon::parse($fetchInfo['start'], $timezone);
>         $end = Carbon::parse($fetchInfo['end'], $timezone);
> 
>         return static::getAppointments($start, $end);
>     }
> 
>     public static function getAppointments(Carbon $start, Carbon $end): array
>     {
>         $appointments = Appointment::query()
>             ->where([
>                 ['start_time', '>=', $start],
>                 ['end_time', '<=', $end],
>             ])
>             ->get();
> 
>         return $appointments->map(function ($appointment) {
>                 return [
>                     'id' => $appointment->id,
>                     'title' => $appointment->title,
>                     'start' => $appointment->start_time,
>                     'end' => $appointment->end_time,
>                 ];
>             })
>             ->toArray();
>     }
> 
>     protected static function getCreateEventFormSchema(): array
>     {
>         return [
>             Forms\Components\TextInput::make('title')
>                 ->required(),
>             Forms\Components\DatePicker::make('start')
>                 ->required(),
>             Forms\Components\DatePicker::make('end')
>                 ->default(null),
>         ];
>     }
> 
>     /**
>      * Triggered when the user clicks an event.
>      *
>      * Commented out so we can save some requests :) Feel free to extend it.
>      * @see https://fullcalendar.io/docs/eventClick
>      */
>     public function onEventClick($event): void
>     {
>         //
>     }
>     
>     /**
>      * Triggered when dragging stops and the event has moved to a different day/time.
>      *
>      * Commented out so we can save some requests :) Feel free to extend it.
>      * @see https://fullcalendar.io/docs/eventDrop
>      */
>     public function onEventDrop($oldEvent, $newEvent, $relatedEvents): void
>     {
>         //
>     }
> 
>     public static function canCreate(): bool
>     {
>         // Returning 'false' will remove the 'Create' button on the calendar.
>         return true;
>     }
> 
>     public static function canEdit(?array $event = null): bool
>     {
>         // Returning 'false' will disable the edit modal when clicking on a event.
>         return true;
>     }
> }
> ```
> 
> The result error like picture below: ![screenshot-filament g24-2022 07 14-21_25_18](https://user-images.githubusercontent.com/88300666/179005924-fe09bd9a-f4f9-4f11-a371-504e5efcf594.png)
> 
> Any help? Thanks in advance

this screenshot does not help anyone. please use the share link to share the error.

also, please check that you are not returning associative arrays, you probably want to use `->values()` instead of `->toArray()`

**Comment by theavuth9** [comment]
Hi @saade I 

> > I'm the same issue and here is my code:
> > Code version:
> > 
> > * php `8.0.x`
> > * filament `^2.0`
> > * filament-fullcalendar `^1.0`
> > 
> > CalendarWidget.php
> > ```
> > class CalendarWidget extends FullCalendarWidget
> > {
> >     /**
> >      * Return events that should be rendered statically on calendar.
> >      */
> >     public function getViewData(): array
> >     {
> >         return static::getAppointments(now()->subMonths(1), now()->addMonths(1));
> >     }
> > 
> >     /**
> >      * FullCalendar will call this function whenever it needs new event data.
> >      * This is triggered when the user clicks prev/next or switches views on the calendar.
> >      */
> >     public function fetchEvents(array $fetchInfo): array
> >     {
> >         $timezone = $this->config('timeZone', config('app.timezone'));
> > 
> >         $start = Carbon::parse($fetchInfo['start'], $timezone);
> >         $end = Carbon::parse($fetchInfo['end'], $timezone);
> > 
> >         return static::getAppointments($start, $end);
> >     }
> > 
> >     public static function getAppointments(Carbon $start, Carbon $end): array
> >     {
> >         $appointments = Appointment::query()
> >             ->where([
> >                 ['start_time', '>=', $start],
> >                 ['end_time', '<=', $end],
> >             ])
> >             ->get();
> > 
> >         return $appointments->map(function ($appointment) {
> >                 return [
> >                     'id' => $appointment->id,
> >                     'title' => $appointment->title,
> >                     'start' => $appointment->start_time,
> >                     'end' => $appointment->end_time,
> >                 ];
> >             })
> >             ->toArray();
> >     }
> > 
> >     protected static function getCreateEventFormSchema(): array
> >     {
> >         return [
> >             Forms\Components\TextInput::make('title')
> >                 ->required(),
> >             Forms\Components\DatePicker::make('start')
> >                 ->required(),
> >             Forms\Components\DatePicker::make('end')
> >                 ->default(null),
> >         ];
> >     }
> > 
> >     /**
> >      * Triggered when the user clicks an event.
> >      *
> >      * Commented out so we can save some requests :) Feel free to extend it.
> >      * @see https://fullcalendar.io/docs/eventClick
> >      */
> >     public function onEventClick($event): void
> >     {
> >         //
> >     }
> >     
> >     /**
> >      * Triggered when dragging stops and the event has moved to a different day/time.
> >      *
> >      * Commented out so we can save some requests :) Feel free to extend it.
> >      * @see https://fullcalendar.io/docs/eventDrop
> >      */
> >     public function onEventDrop($oldEvent, $newEvent, $relatedEvents): void
> >     {
> >         //
> >     }
> > 
> >     public static function canCreate(): bool
> >     {
> >         // Returning 'false' will remove the 'Create' button on the calendar.
> >         return true;
> >     }
> > 
> >     public static function canEdit(?array $event = null): bool
> >     {
> >         // Returning 'false' will disable the edit modal when clicking on a event.
> >         return true;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The result error like picture below: ![screenshot-filament g24-2022 07 14-21_25_18](https://user-images.githubusercontent.com/88300666/179005924-fe09bd9a-f4f9-4f11-a371-504e5efcf594.png)
> > Any help? Thanks in advance
> 
> this screenshot does not help anyone. please use the share link to share the error.
> 
> also, please check that you are not returning associative arrays, you probably want to use `->values()` instead of `->toArray()`

I already replace  `->toArray()` to `->values()` and still the same error when use `use CanManageEvents;`.

Sorry, this is a local dev project and it's also just testing so I can't share the link with the error with you.

**Comment by saade** [comment]
> Hi @saade I
> 
> > > I'm the same issue and here is my code:
> > > Code version:
> > > 
> > > * php `8.0.x`
> > > * filament `^2.0`
> > > * filament-fullcalendar `^1.0`
> > > 
> > > CalendarWidget.php
> > > ```
> > > class CalendarWidget extends FullCalendarWidget
> > > {
> > >     /**
> > >      * Return events that should be rendered statically on calendar.
> > >      */
> > >     public function getViewData(): array
> > >     {
> > >         return static::getAppointments(now()->subMonths(1), now()->addMonths(1));
> > >     }
> > > 
> > >     /**
> > >      * FullCalendar will call this function whenever it needs new event data.
> > >      * This is triggered when the user clicks prev/next or switches views on the calendar.
> > >      */
> > >     public function fetchEvents(array $fetchInfo): array
> > >     {
> > >         $timezone = $this->config('timeZone', config('app.timezone'));
> > > 
> > >         $start = Carbon::parse($fetchInfo['start'], $timezone);
> > >         $end = Carbon::parse($fetchInfo['end'], $timezone);
> > > 
> > >         return static::getAppointments($start, $end);
> > >     }
> > > 
> > >     public static function getAppointments(Carbon $start, Carbon $end): array
> > >     {
> > >         $appointments = Appointment::query()
> > >             ->where([
> > >                 ['start_time', '>=', $start],
> > >                 ['end_time', '<=', $end],
> > >             ])
> > >             ->get();
> > > 
> > >         return $appointments->map(function ($appointment) {
> > >                 return [
> > >                     'id' => $appointment->id,
> > >                     'title' => $appointment->title,
> > >                     'start' => $appointment->start_time,
> > >                     'end' => $appointment->end_time,
> > >                 ];
> > >             })
> > >             ->toArray();
> > >     }
> > > 
> > >     protected static function getCreateEventFormSchema(): array
> > >     {
> > >         return [
> > >             Forms\Components\TextInput::make('title')
> > >                 ->required(),
> > >             Forms\Components\DatePicker::make('start')
> > >                 ->required(),
> > >             Forms\Components\DatePicker::make('end')
> > >                 ->default(null),
> > >         ];
> > >     }
> > > 
> > >     /**
> > >      * Triggered when the user clicks an event.
> > >      *
> > >      * Commented out so we can save some requests :) Feel free to extend it.
> > >      * @see https://fullcalendar.io/docs/eventClick
> > >      */
> > >     public function onEventClick($event): void
> > >     {
> > >         //
> > >     }
> > >     
> > >     /**
> > >      * Triggered when dragging stops and the event has moved to a different day/time.
> > >      *
> > >      * Commented out so we can save some requests :) Feel free to extend it.
> > >      * @see https://fullcalendar.io/docs/eventDrop
> > >      */
> > >     public function onEventDrop($oldEvent, $newEvent, $relatedEvents): void
> > >     {
> > >         //
> > >     }
> > > 
> > >     public static function canCreate(): bool
> > >     {
> > >         // Returning 'false' will remove the 'Create' button on the calendar.
> > >         return true;
> > >     }
> > > 
> > >     public static function canEdit(?array $event = null): bool
> > >     {
> > >         // Returning 'false' will disable the edit modal when clicking on a event.
> > >         return true;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The result error like picture below: ![screenshot-filament g24-2022 07 14-21_25_18](https://user-images.githubusercontent.com/88300666/179005924-fe09bd9a-f4f9-4f11-a371-504e5efcf594.png)
> > > Any help? Thanks in advance
> > 
> > 
> > this screenshot does not help anyone. please use the share link to share the error.
> > also, please check that you are not returning associative arrays, you probably want to use `->values()` instead of `->toArray()`
> 
> I already replace `->toArray()` to `->values()` and still the same error when use `use CanManageEvents;`.
> 
> Sorry, this is a local dev project and it's also just testing so I can't share the link with the error with you.

you can. just click on the "Share" button on the top menubar (see screenshot)

**Comment by theavuth9** [comment]
> > Hi @saade I
> > > > I'm the same issue and here is my code:
> > > > Code version:
> > > > 
> > > > * php `8.0.x`
> > > > * filament `^2.0`
> > > > * filament-fullcalendar `^1.0`
> > > > 
> > > > CalendarWidget.php
> > > > ```
> > > > class CalendarWidget extends FullCalendarWidget
> > > > {
> > > >     /**
> > > >      * Return events that should be rendered statically on calendar.
> > > >      */
> > > >     public function getViewData(): array
> > > >     {
> > > >         return static::getAppointments(now()->subMonths(1), now()->addMonths(1));
> > > >     }
> > > > 
> > > >     /**
> > > >      * FullCalendar will call this function whenever it needs new event data.
> > > >      * This is triggered when the user clicks prev/next or switches views on the calendar.
> > > >      */
> > > >     public function fetchEvents(array $fetchInfo): array
> > > >     {
> > > >         $timezone = $this->config('timeZone', config('app.timezone'));
> > > > 
> > > >         $start = Carbon::parse($fetchInfo['start'], $timezone);
> > > >         $end = Carbon::parse($fetchInfo['end'], $timezone);
> > > > 
> > > >         return static::getAppointments($start, $end);
> > > >     }
> > > > 
> > > >     public static function getAppointments(Carbon $start, Carbon $end): array
> > > >     {
> > > >         $appointments = Appointment::query()
> > > >             ->where([
> > > >                 ['start_time', '>=', $start],
> > > >                 ['end_time', '<=', $end],
> > > >             ])
> > > >             ->get();
> > > > 
> > > >         return $appointments->map(function ($appointment) {
> > > >                 return [
> > > >                     'id' => $appointment->id,
> > > >                     'title' => $appointment->title,
> > > >                     'start' => $appointment->start_time,
> > > >                     'end' => $appointment->end_time,
> > > >                 ];
> > > >             })
> > > >             ->toArray();
> > > >     }
> > > > 
> > > >     protected static function getCreateEventFormSchema(): array
> > > >     {
> > > >         return [
> > > >             Forms\Components\TextInput::make('title')
> > > >                 ->required(),
> > > >             Forms\Components\DatePicker::make('start')
> > > >                 ->required(),
> > > >             Forms\Components\DatePicker::make('end')
> > > >                 ->default(null),
> > > >         ];
> > > >     }
> > > > 
> > > >     /**
> > > >      * Triggered when the user clicks an event.
> > > >      *
> > > >      * Commented out so we can save some requests :) Feel free to extend it.
> > > >      * @see https://fullcalendar.io/docs/eventClick
> > > >      */
> > > >     public function onEventClick($event): void
> > > >     {
> > > >         //
> > > >     }
> > > >     
> > > >     /**
> > > >      * Triggered when dragging stops and the event has moved to a different day/time.
> > > >      *
> > > >      * Commented out so we can save some requests :) Feel free to extend it.
> > > >      * @see https://fullcalendar.io/docs/eventDrop
> > > >      */
> > > >     public function onEventDrop($oldEvent, $newEvent, $relatedEvents): void
> > > >     {
> > > >         //
> > > >     }
> > > > 
> > > >     public static function canCreate(): bool
> > > >     {
> > > >         // Returning 'false' will remove the 'Create' button on the calendar.
> > > >         return true;
> > > >     }
> > > > 
> > > >     public static function canEdit(?array $event = null): bool
> > > >     {
> > > >         // Returning 'false' will disable the edit modal when clicking on a event.
> > > >         return true;
> > > >     }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The result error like picture below: ![screenshot-filament g24-2022 07 14-21_25_18](https://user-images.githubusercontent.com/88300666/179005924-fe09bd9a-f4f9-4f11-a371-504e5efcf594.png)
> > > > Any help? Thanks in advance
> > > 
> > > 
> > > this screenshot does not help anyone. please use the share link to share the error.
> > > also, please check that you are not returning associative arrays, you probably want to use `->values()` instead of `->toArray()`
> > 
> > 
> > I already replace `->toArray()` to `->values()` and still the same error when use `use CanManageEvents;`.
> > Sorry, this is a local dev project and it's also just testing so I can't share the link with the error with you.
> 
> you can. just click on the "Share" button on the top menubar (see screenshot)

Oh I see it, thanks and this the link share https://flareapp.io/share/DPygRKQ5#F98

**Comment by wychoong** [comment]
Can you do the following
1) remove `getCreateEventFormSchema` method temporarily see if the error goes away
2) share complete code with namespaces and use

**Comment by theavuth9** [comment]
> Can you do the following
> 
> 1. remove `getCreateEventFormSchema` method temporarily see if the error goes away
> 2. share complete code with namespaces and use

This is complete code:

```php
<?php

namespace App\Filament\Widgets;

use Carbon\Carbon;
use App\Models\Appointment;
use Saade\FilamentFullCalendar\Widgets\FullCalendarWidget;
use Saade\FilamentFullCalendar\Widgets\Concerns\CanManageEvents;
use Saade\FilamentFullCalendar\Widgets\Concerns\CantManageEvents;
use Filament\Forms;

class CalendarWidget extends FullCalendarWidget
{
    use CanManageEvents;

    /**
     * FullCalendar will call this function whenever it needs new event data.
     * This is triggered when the user clicks prev/next or switches views on the calendar.
     */
    public function fetchEvents(array $fetchInfo): array
    {
        $timezone = $this->config('timeZone', config('app.timezone'));

        $start = Carbon::parse($fetchInfo['start'], $timezone);
        $end = Carbon::parse($fetchInfo['end'], $timezone);

        return static::getAppointments($start, $end);
    }

    public static function getAppointments(Carbon $start, Carbon $end, array $ignorableIds = []): array
    {
        $appointments = Appointment::query()
            ->where([
                ['start_time', '>=', $start],
                ['end_time', '<=', $end],
            ])
            ->whereNotIn('id', $ignorableIds)
            ->get();

        $listapps = $appointments->map(function ($appointment) {
                return [
                    'id' => $appointment->id,
                    'title' => $appointment->title,
                    'start' => $appointment->start_time,
                    'end' => $appointment->end_time,
                ];
            });

        return $listapps->toArray();
    }

}
```

and the error is the same https://flareapp.io/share/omwglw9m#F98

**Comment by wychoong** [comment]
1) remove `use CanManageEvents;` and see if the error goes away
2) if previous step is ok then put `getCreateEventFormSchema` back and test again
