### ISSUE TITLE
Using this widget in a resource's page

### ISSUE THREAD

**Issue by invaders-xx** [saade/filament-fullcalendar#33]
I have different plannings and I would like to add this widget in a resource. but there is a conflict in using $this->record as this property is used in Filament widget's resource to refer to the record edited or viewed.

**Comment by wychoong** [comment]
Sorry this was introduced by #18

**Comment by saade** [comment]
> Sorry this was introduced by #18

Yep :/, we can use `Model $event` and `int $event_id` intead of `record`

**Comment by wychoong** [comment]
yeah but that can't be helped much. maybe introduce few more meaningful features and bump it to v2? else need to come up with a way to detect it's used in a resource page and switch to use `$event` and `$event_id`

**Comment by saade** [comment]
Sorry, i only use the calendar for displaying data, maybe i'm missing something but, yhy not always use `$event`?

**Comment by wychoong** [comment]
you mean why switch for resource page only? in my previous comment is for no breaking change

**Comment by saade** [comment]
i think i prefer using $event in both for consistency, but i agree with adding more features before releasing v2.

I dont have any new features planned, have you?

**Comment by wychoong** [comment]
I don’t at the moment

**Comment by invaders-xx** [comment]
#41 PR implements this change
