### ISSUE TITLE
Using event form with relations

### ISSUE THREAD

**Issue by invaders-xx** [saade/filament-fullcalendar#43]
I am not able to make it working with an event form using relations : a select or  repeater.
Simple form :
```php
protected static function getCreateEventFormSchema(): array
    {
        return [
            Forms\Components\Select::make('planning_id')
                ->label(__('Planning'))
                ->validationAttribute(__('Planning'))
                ->searchable()
                ->relationship('planning', 'name')
                ->preload()
                ->required(),
            Forms\Components\DatePicker::make('start_at')
                ->required(),
            Forms\Components\DatePicker::make('end_at')
                ->default(null),
        ];
    }
```

I got : Call to a member function planning() on null
Event if the relation exists

**Comment by webtamizhan** [comment]
`->model(YourModelName::class)`

with Select or Repeater.

**Comment by invaders-xx** [comment]
thanks but it's not how it works in that case, we are talking about Repeater and Select which belong to a relation and not a model.

**Comment by tiagof** [comment]
> `->model(YourModelName::class)`
> 
> with Select or Repeater.

Hi, having this same issue and this solution doesn't seem to work:
using `->model(YourModelName::class)` does bypass the exception mentioned in the op, but the relation is not populated nor can be edited.

@invaders-xx did you get it working?

**Comment by invaders-xx** [comment]
@tiagof, I didn't get it working

**Comment by tiagof** [comment]
@saade any ideia/suggestion?

**Comment by tiagof** [comment]
Have a look at #47 .

You'll need to define, in your Widget class, otherwise you'll still get the exception

```php
class MyWidget extends FullCalendarWidget
{

    protected function getFormModel(): Model|string|null
    {
        return $this->event ?? MyEventModel::class;
    }

    // Resolve Event record into Model property
    public function resolveEventRecord(array $data): MyEventModel
    {
        return MyEventModel::find($data['id']);
    }

```

**Comment by invaders-xx** [comment]
As you reverted #47, it's not working

**Comment by dbrnjh47** [comment]
// https://github.com/saade/filament-fullcalendar/issues/122

```
protected function getFormModel(): Model|string|null
    {
        return $this->event ?? PostScheduled::class;
    }

    public function resolveEventRecord(array $data): PostScheduled
    {
        return PostScheduled::find($data['id']);
    }
```
