### ISSUE TITLE
ResourceTimeline View - Alpine Expression Error: t is undefined

### ISSUE THREAD

**Issue by jpedryc** [saade/filament-fullcalendar#79]
Hi :wave: 

I'm trying to figure out how to set up the resourceTimeline view added by @steveadamsfixedit and encountered some issues:

![fullcalendar_t_error](https://user-images.githubusercontent.com/38433190/235799329-0020323c-d290-4656-b272-39c1a09783a3.png)

I think there is something missing while registering the calendarComponent plugin in Alpine. I was thinking that maybe the **initialDate** should be added to filament-fullcalendar config file additionally, but it did not fix it.

Do you have some ideas where to start? Thank you in advance!

###### My config file:

```PHP
<?php

// ...

return [
    'timeZone' => config('app.timezone'),
    'locale' => config('app.locale'),
    'resources' => [],
    'plugins' => ['dayGridPlugin, timeGridPlugin, listPlugin, resourceTimelinePlugin, interactionPlugin, momentPlugin, momentTimezonePlugin'],
    'initialView' => 'resourceTimelineMonth',
    'initialDate' => Carbon::now()->format('Y-m-d'),
    'headerToolbar' => [
        'left' => 'prev,next today',
        'center' => 'title',
        'right' => 'dayGridMonth,dayGridWeek,dayGridDay',
    ],
    'views' => [
        'timelineMonth' => [
            'type' => 'resourceTimeline',
            'duration' => [ 'month' => 1 ],
            'buttonText' =>'Resources',
        ],
    ],
    'navLinks' => true,
    'editable' => true,
    'selectable' => true,
    'dayMaxEvents' => true,
];
```

**Comment by jackleblack-kpt** [comment]
Same error here, did you get it ?

**Comment by jpedryc** [comment]
@jackleblack-kpt Needed more customization anyways - ended up using Full Calendar directly (vanilla style - not through this wrapper).

**Comment by saade** [comment]
Hey, if you guys are using v3, please give it a try and see if you get any issues
