### ISSUE TITLE
Error if the event ID is a UUID

### ISSUE THREAD

**Issue by billmn** [saade/filament-fullcalendar#80]
Using a UUID, instead of an auto-incremental ID, results in the following error when clicking on an event:
```
Cannot assign string to property Saade\FilamentFullCalendar\Widgets\FullCalendarWidget::$event_id of type ?int
```

This because in `CanManageEvents` trait, the `$event_id` property is typed as an integer.
I think it can be typed as a string without causing any BC.

**Comment by saade** [comment]
sorry for the delay, its merged
