### ISSUE TITLE
V3 compatibility

### ISSUE THREAD

**Issue by saade** [saade/filament-fullcalendar#93]
### Discussed in https://github.com/saade/filament-fullcalendar/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **tonypartridge** May 25, 2023</sup>
Any plans for Filament V3 yet?</div>

**Comment by TonyPartridgeR** [comment]
There is already a pull request #88

**Comment by saade** [comment]
Hello friends.

Just released v3.0.0-beta1.

PLEASE READ CAREFULLY:

- This is a first-pass release for supporting v3.
- There WILL BE BRAKING CHANGES when the final v3.0.0 is released.
- The docs are not updated yet. But there are no braking changes for now.


Thanks for everyone who opened a PR for supporting v3. :yellow_heart:
