### ISSUE TITLE
Failed to find '@fullcalendar/common/main.css'

### ISSUE THREAD

**Issue by it-dubbelglas** [saade/filament-fullcalendar#96]
Hi,

By upgrading from v1.8.0 to v1.9.0 my project (npm) broke.

I get the following error message, when executing the `npm run dev` command
```shell
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '@fullcalendar/common/main.css'
```

I'm making use of the customization feature described in your documentation's [Styling](https://github.com/saade/filament-fullcalendar#styling)-chapter, having the following line in my `./resources/css/app.css`:
```css
@import '../../vendor/saade/filament-fullcalendar/resources/css/filament-fullcalendar.css';
```

My webpack.mix.js looks like this:
```js
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss'),
    ])
```

I think the change you made to [resources/css/filament-fullcalendar.css](https://github.com/saade/filament-fullcalendar/commit/465e50a8bf4b4beddfb130e886221d0c9a48e954#diff-f7ba1f251d94d20f45bb31f0966c3fb4ba295aef919ebe2243204172d363acbe) in your last commit, broke the building process.

Am I doing something wrong? How to fix this?

**Comment by kamilst96** [comment]
First issue is that `filament-fullcalendar.css` assumes there will be `node_modules` populated within package root, but it isn't there. 

- If you use `@import '../../../../../node_modules` as base folder, and install fullcalendar dependencies mentioned in package root, build will succeed.

```json
"@fullcalendar/core": "^5.11.5",
"@fullcalendar/daygrid": "^5.11.5",
"@fullcalendar/interaction": "^5.11.5",
"@fullcalendar/list": "^5.11.5",
"@fullcalendar/moment": "^5.11.5",
"@fullcalendar/moment-timezone": "^5.11.5",
"@fullcalendar/resource-timeline": "^5.11.3",
"@fullcalendar/rrule": "^5.11.5",
"@fullcalendar/timegrid": "^5.11.5",
```

But it still bugs out beyond my level of competence.

![image](https://github.com/saade/filament-fullcalendar/assets/37311362/1957da91-4b44-4756-b8e3-b134c572220b)

I suggest freezing package at 1.8.0 and wait. I'll be probing around, but saade will probably fix it soon.

**Comment by sergioraldana** [comment]
Similar here: 

<img width="890" alt="Captura de pantalla 2023-07-10 a la(s) 17 59 32" src="https://github.com/saade/filament-fullcalendar/assets/60765721/3e4047fd-ce0b-4882-9807-c4ee0f7c1e99">

**Comment by it-dubbelglas** [comment]
v1.9.1 with commit 5c9276044665bbcbb1fd944bdbb8ea42a152eb43 fixed the issue. Thanks @saade !

**Comment by bobwurtz** [comment]
I still experience this issue with `v1.9.1` and `v1.9.2`. Downgrading to `v1.8.0` fixed this for me. Can this be reopened?

**Comment by kamilst96** [comment]
@bobwurtz did you include the newly required config?

```php
 'plugins' => [
        'dayGrid' => true,
        'timeGrid' => true,
        'interaction' => true,
        'list' => true,
        'rrule' => true,
        'resourceTimeline' => true,
    ],
```

**Comment by bobwurtz** [comment]
@kamilst96 I did not. My mistake - I should have read the updated docs more carefully.
