### ISSUE TITLE
Invalid license key

### ISSUE THREAD

**Issue by juanDuarteMolina** [saade/filament-fullcalendar#97]
Hi
This message appear at the botom of the calendar

"Your license key is invalid. [More Info]"
There is a way to downgrade the package?

**Comment by TonyPartridgeR** [comment]
This is caused by:

https://github.com/saade/filament-fullcalendar/commit/614eed11d25f2b1c886f68a2b8337e15c00fde29

timeGrid is a premium feature. @saade  can you review and condition adding a license key in?

**Comment by juanDuarteMolina** [comment]
Thanks for the clue ...

'resourceTimeline' => false,

solve the issue
